const MoviesTypes = {
  ADD_LIKE: 'ADD_LIKE',
  REMOVE_LIKE: 'REMOVE_LIKE',
  CHANGE_MOVIE_RATING: 'CHANGE_MOVIE_STARS',
  SEARCH_VALUE_CHANGED: 'SEARCH_VALUE_CHANGED',
  SORT_BY_LIKES: 'SORT_BY_LIKES',
  SORT_BY_RATING: 'SORT_BY_RATING',
  RESET_SORTING: 'RESET_SORTING',
  EDIT_MOVIE: 'EDIT_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE'
};

export default MoviesTypes;
