const MoviesTypes = {
  CHANGE_LIKES: 'CHANGE_LIKES',
  REMOVE_LIKE: 'REMOVE_LIKE',
  CHANGE_MOVIE_RATING: 'CHANGE_MOVIE_STARS',
  SEARCH_VALUE_CHANGED: 'SEARCH_VALUE_CHANGED',
  SORT_BY_LIKES: 'SORT_BY_LIKES',
  SORT_BY_RATING: 'SORT_BY_RATING',
  RESET_SORTING: 'RESET_SORTING',
  EDIT_MOVIE: 'EDIT_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE',
  MOVIES_LOADING_START: 'MOVIES_LOADING_START',
  MOVIES_LOADED: 'MOVIES_LOADED',
  MOVIES_LOADING_FAILED: 'MOVIES_LOADING_FAILED',
  MOVIES_UPDATED: 'MOVIES_UPDATED',
  ACTIVE_MOVIE_UPDATED: 'ACTIVE_MOVIE_UPDATED',
  ACTORS_LOADING_START: 'MOVIES_LOADING_START',
  ACTORS_LOADING_FAILED: 'ACTORS_LOADING_FAILED',
  ACTORS_DATA_LOADED: 'ACTORS_DATA_LOADED',
  SHOW_ERROR_MESSAGE: 'SHOW_ERROR_MESSAGE',
  HIDE_ERROR_MESSAGE: 'HIDE_ERROR_MESSAGE'
};

export default MoviesTypes;
